### ISSUE TITLE
Simplest sample code didn't produce the expected results

### ISSUE THREAD

**Issue by fbarbuto** [olivierverdier/odelab#2]
Hello,

The [sample code](http://olivierverdier.github.io/odelab/rst/intro.html) provided in odelab's documentation page:

```
from odelab import Solver, System
from odelab.scheme.classic import ExplicitEuler

def f(t,u):
    return -u

s = Solver(scheme=ExplicitEuler(.1), system=System(f))
s.initialize(u0=1.)
s.run(1.)

s.plot()
```

does not plot anything, and yet it ends normally (that is, no error message is displayed). Whatever might have happened? I'm running Windows 7 64-bit, Python 2.7.12.

Any help will be much appreciated.

Fausto

**Comment by olivierverdier** [comment]
If there is no error message, it means that it works. The data is available in the solver object. The plot is independent of odelab, you may have to look elsewhere for the reason why the plot does not show.
